include:
  - "app/**/*"
  - "lib/**/*.rb"
  - "config/**/*.rb"
  - "spec/**/*.rb"
exclude:
  - test/**/*
  - vendor/**/*
  - ".bundle/**/*"
  - bin/**/*
require:
  - actioncable
  - actionmailer
  - actionpack
  - actionview
  - activejob
  - activemodel
  - activerecord
  - activestorage
  - activesupport
  - rspec-rails
plugins:
  - solargraph-rails
domains: []
reporters:
  - rubocop
max_files: 5000
