version: '3.8'

x-assets: &default-assets
  build:
    context: "."
    target: "assets"
    args:
      - "UID=${UID:-1000}"
      - "GID=${GID:-1000}"
      - "RAILS_ENV=${RAILS_ENV:-development}"
      - "NODE_ENV=${NODE_ENV:-development}"
  env_file:
    - ".env"
  profiles: ["assets"]
  restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
  stop_grace_period: "3s"
  tty: true
  volumes:
    - ".:/project"

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${PG_DB_USER}
      - POSTGRES_PASSWORD=${PG_DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  redis:
    image: 'redis:6-alpine'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'

  sidekiq:
    depends_on:
      - db
      - redis
    build: .
    command: bundle exec sidekiq
    volumes:
      - '.:/project'
      - '/project/tmp'
    environment:
      - REDIS_URL_SIDEKIQ=${REDIS_URL_SIDEKIQ}

  web:
    depends_on:
      - db
      - redis
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0' -e ${RAILS_ENV}"
    ports:
      - '3000:${APP_PORT:-3000}'
    volumes:
      - '.:/project'
    environment:
      - REDIS_URL_SIDEKIQ=${REDIS_URL_SIDEKIQ}
    env_file:
      - ".env"
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    stop_grace_period: "3s"
    tty: true

  js:
    <<: *default-assets
    command: "yarn build"

volumes:
  db:
    # driver: local
  redis:
